#!/bin/bash

# Deployment folder
WEB_ROOT="$HOME/public_html/private/10260"

# Path to GIT bare repo
GIT_DIR="$HOME/repo/myassignments.git"

# Backup folder
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
BACKUP_DIR="$HOME/public_html/private/backup/"
mkdir -p "$BACKUP_DIR/$TIMESTAMP"

# Backup current deployment
echo "Backing up current deployment to $BACKUP_DIR/$TIMESTAMP..."

# Aborts Deployment if deployment fails.
cp -r "$WEB_ROOT/" "$BACKUP_DIR/$TIMESTAMP" || {
        echo "Backup Failed! Aborting Deployment.";
        exit 1;
}

# Deploy Lastest Changes
echo "Deploying Changes to $WEB_ROOT"

git --work-tree="$WEB_ROOT" --git-dir="$GIT_DIR" checkout -f

echo "Deployment successful."
